default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
adapter: postgresql
  database: railway
  username: postgres
  password: EMkME6YI8c3N9ozI54PW
  host: containers-us-west-53.railway.app
  port: 7489
  pool: 5
 